### ISSUE TITLE
mysql table

### ISSUE THREAD

**Issue by 7-Lanan** [littleblackdot/OrderSys#1]
博主，想询问一下你这个qt项目的数据库表结构是什么样的，感谢！！！

**Comment by littleblackdot** [comment]
> 
你好，我写这个项目的环境暂时找不到了，所以数据库也没了，但是有一些我当初写个项目时的参考视频，项目也基本上是复现视频上的功能，具体的数据库表结构可以从里面获取参考。
网盘链接：
链接：https://pan.baidu.com/s/1UO_qcYW72HBPCfnMPFIvXw 
提取码：nwcg

**Comment by 7-Lanan** [comment]
> > 
> 
> 你好，我写这个项目的环境暂时找不到了，所以数据库也没了，但是有一些我当初写个项目时的参考视频，项目也基本上是复现视频上的功能，具体的数据库表结构可以从里面获取参考。 网盘链接： 链接：https://pan.baidu.com/s/1UO_qcYW72HBPCfnMPFIvXw 提取码：nwcg

非常感谢！！！

**Comment by 7-Lanan** [comment]
博主，你好！
       再向你请教一下，服务器运行后的登录界面的问题：请问数据库结构有啥问题吗
![{0295~6IV{MCM$LFZ9JH7QL](https://user-images.githubusercontent.com/101372483/163671248-9a1e7511-6be5-48e9-ad7d-f83f888d5764.png)

**Comment by littleblackdot** [comment]
> 博主，你好！ 再向你请教一下，服务器运行后的登录界面的问题：请问数据库结构有啥问题吗 ![{0295~6IV{MCM$LFZ9JH7QL](https://user-images.githubusercontent.com/101372483/163671248-9a1e7511-6be5-48e9-ad7d-f83f888d5764.png)

wight.cpp中密码判断逻辑部分的代码：
if(query.value(3) != pwd){
        QMessageBox::warning(this, "提示", "密码错误");
        return ;
    }
说明密码是数据库user表里的第四个字段，(如果你没有对代码做一些适配性的改动)那用户表的组成字段因该依次为：UserId，UserType, UserName, UserPassword,前三个字段可以从下面的代码中推测出来：
User user(query.value(0).toInt(), (UserType)query.value(1).toInt(), query.value(2).toString()); //wight.cpp第60行
User::User(int id, UserType type, QString name):id(id), userType(type), name(name){}    //User类构造函数

**Comment by 7-Lanan** [comment]
> > 博主，你好！ 再向你请教一下，服务器运行后的登录界面的问题：请问数据库结构有啥问题吗 ![{0295~6IV{MCM$LFZ9JH7QL](https://user-images.githubusercontent.com/101372483/163671248-9a1e7511-6be5-48e9-ad7d-f83f888d5764.png)
> 
> wight.cpp中密码判断逻辑部分的代码： if(query.value(3) != pwd){ QMessageBox::warning(this, "提示", "密码错误"); return ; } 说明密码是数据库user表里的第四个字段，(如果你没有对代码做一些适配性的改动)那用户表的组成字段因该依次为：UserId，UserType, UserName, UserPassword,前三个字段可以从下面的代码中推测出来： User user(query.value(0).toInt(), (UserType)query.value(1).toInt(), query.value(2).toString()); //wight.cpp第60行 User::User(int id, UserType type, QString name):id(id), userType(type), name(name){} //User类构造函数

已知悉，感谢博主！

**Comment by 7-Lanan** [comment]
博主，再次请教：
![image](https://user-images.githubusercontent.com/101372483/163972523-02e11834-ad95-4254-a5ea-dbd4b30db811.png)

**Comment by littleblackdot** [comment]
> 博主，再次请教： ![image](https://user-images.githubusercontent.com/101372483/163972523-02e11834-ad95-4254-a5ea-dbd4b30db811.png)

这个我就不太清楚了，要不你把数据库脚本发我，我本地把操作复现一下，也可能是项目的bug，这个项目写完我就简单试了一下功能就没有动了。这是我qq： 2602690396，不嫌麻烦的话可以加一下，讨论一下这个项目
